### ISSUE TITLE
利用制限時にリトライする機能を組み込みたい

### ISSUE THREAD

**Issue by kokuyouwind** [krayinc/docbase-ruby#16]
DocBase APIでは1時間に300回までしかリクエストを受け付けず、それ以上のリクエストについてはステータスコード429を返すという仕様が存在します。([参考](https://help.docbase.io/posts/45703#%E5%88%A9%E7%94%A8%E5%88%B6%E9%99%90))
このケースについて、現状ではFaraday Responseがそのまま返されますが、レスポンスに含まれる`X-RateLimit-Reset`まで待機する処理をgemに組み込むほうが使い勝手が良いと思います。

[esa-ruby](https://github.com/esaio/esa-ruby)では[response.statusに応じてwait処理を挟んでおり](https://github.com/esaio/esa-ruby/blob/master/lib/esa/client.rb#L45-L54)、同様の対応を行うことで実現できるはずです。
また用途によっては待たずにエラーを返してほしい場合もありそうですが、こちらもesa-rubyと同様に[initializeで利用制限時の挙動を制御するフラグを渡す](https://github.com/esaio/esa-ruby/blob/master/lib/esa/client.rb#L11-L17)のが良いかと思います。

**Comment by ttakuru88** [comment]
ありがとうございます、便利そうですね。
現在進んで対応予定ではありませんが、PRいただければ確認します。

**Comment by mochizuki-pg** [comment]
@ttakuru88 
PR出してみましたので、確認お願いします
