### ISSUE TITLE
groupsでnameやpageの指定ができない

### ISSUE THREAD

**Issue by kokuyouwind** [krayinc/docbase-ruby#17]
[グループ検索API](https://help.docbase.io/posts/92978)ではnameを指定したグループ名完全一致での取得や取得ページの指定ができますが、[#groups メソッド](https://github.com/krayinc/docbase-ruby/blob/master/lib/docbase/client.rb#L30-L32)では引数を受け付けておらず、最初のページの取得しかできません。
これだと全件の取得や、目的とするグループが2ページ目以降にある場合のグループID取得などが行えないため、[#users メソッド](https://github.com/krayinc/docbase-ruby/blob/master/lib/docbase/client.rb#L22-L24) と同様に引数を受け付けるようにしたいです。

**Comment by ttakuru88** [comment]
ありがとうございます、こちらバグでした。
修正をしていきます。

**Comment by j-sakamoto** [comment]
@kokuyouwind @ttakuru88 

ありがとうございました。
こちらv2.1.1にて修正・リリースを行いましたのでcloseとさせていただきます。
