### ISSUE TITLE
バージョン指定でundefined method `strip' for 1:Integerが発生する

### ISSUE THREAD

**Issue by Taka571** [krayinc/docbase-ruby#8]
現在公開されているgemのバージョンを0.3.0.1→1.0.0にアップデートしたところ、表題のエラーが発生しましたのでご報告いたします。原因はheadersでのバージョン指定('X-Api-Version')の値で数値型を渡してしまっていることのようです。("1"と文字列型を送信することで問題なく動作しました)

https://github.com/krayinc/docbase-ruby/blob/429ea7c4ab5fa4cf1733a122d743aac90c2d17a8/lib/docbase/client.rb#L134-L141

エラー発生箇所はdocbase→faraday→ruby net/httpの以下の箇所(value.strip)です。

https://github.com/ruby/ruby/blob/ddf5020e4fcae5ed28a064af10124a032590452f/lib/net/http/header.rb#L13-L28

```ruby
  def initialize_http_header(initheader)
    @header = {}
    return unless initheader
    initheader.each do |key, value|
      warn "net/http: duplicated HTTP header: #{key}", uplevel: 3 if key?(key) and $VERBOSE
      if value.nil?
        warn "net/http: nil HTTP header: #{key}", uplevel: 3 if $VERBOSE
      else
        value = value.strip # raise error for invalid byte sequences
        if value.count("\r\n") > 0
          raise ArgumentError, "header #{key} has field value #{value.inspect}, this cannot include CR/LF"
        end
        @header[key.downcase.to_s] = [value]
      end
    end
  end
```

リファレンス
https://docs.ruby-lang.org/ja/latest/class/Net=3a=3aHTTP.html
>header が nil でなければ、リクエストを送るときにその内容を HTTP ヘッダとして 送ります。 header は { 'Accept' = > '*/*', ... } という 形のハッシュでなければいけません。

**Comment by ttakuru88** [comment]
ありがとうございます！

**Comment by ttakuru88** [comment]
修正をv1.0.1としてリリースしました 🙇
